server:
  port: 8080

spring:
  application:
    name: springboot-monitoring
  zipkin:
    base-url: http://localhost:9411
    enabled: false
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elastic
      password: changeme
      connection-timeout: 10s
      read-timeout: 30s



logging:
  file:
    name: springboot-monitoring.log
  level.root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
